"""Initial migration

Revision ID: 029be2606cee
Revises: 
Create Date: 2025-02-23 02:58:07.989404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029be2606cee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bubbles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bubble1_id', sa.UUID(), nullable=False),
    sa.Column('bubble2_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bubble1_id'], ['bubbles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bubble2_id'], ['bubbles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('bubbles')
    # ### end Alembic commands ###
