"""Add x and y coordinates to bubbles

Revision ID: 5f837d250d3e
Revises: 6d6c02a63a7e
Create Date: 2025-02-23 15:52:50.119728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f837d250d3e'
down_revision: Union[str, None] = '6d6c02a63a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bubbles', sa.Column('x', sa.Float(), nullable=False))
    op.add_column('bubbles', sa.Column('y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bubbles', 'y')
    op.drop_column('bubbles', 'x')
    # ### end Alembic commands ###
